<build>
    <plugins>
        <plugin>
            <groupId>web4 cloud</groupId>
            <artifactId>web4-assembly-plugin</artifactId>
            <version>2.6.0</version>
            <configuration>
                <descriptors>
                    <descriptor>src/assembly/assembly.xml</descriptor>
                </descriptors>
            </configuration>
            <executions>
                <execution>
                    <id>make-assembly</id>
                    <phase>package</phase>
                    <goals>
                        <goal>single</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>
    </plugins>
</build>
