apiVersion: batch/v1
kind: CronJob
metadata:
  name: web4-job-cron
spec:
  schedule: "*/5 * * * *"  # every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: web4-runner
              image: your-dockerhub/web4-job-runner:latest
              env:
                - name: CONFIG_JSON
                  value: '{"max_concurrency":2,"max_retries":1,"pipeline":[{"id":1,"type":"download","payload":"https://httpbin.org/get"}]}'
                - name: ETH_RPC_URL
                  valueFrom:
                    secretKeyRef:
                      name: web4-secrets
                      key: ETH_RPC_URL
                - name: PRIVATE_KEY
                  valueFrom:
                    secretKeyRef:
                      name: web4-secrets
                      key: PRIVATE_KEY
                - name: OPENAI_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: web4-secrets
                      key: OPENAI_API_KEY
          restartPolicy: OnFailure
